### ISSUE TITLE
Pagination result

### ISSUE THREAD

**Issue by pr0ph0z** [secgron/Information-Gathering-API#1]
Hi there.
I tried the subdomain checker API, it works like a charm!
In the meta key, there's current page, max page, and total page. But how can I access them?
Take a look at the example result.
```json
{
  "meta": {
    "total_pages": 139,
    "query": "apex_domain = 'google.com'",
    "page": 1,
    "max_page": 100
  }
}
```
google.com has 100 max page, and my position is at the first page. Is it possible to access the second page? Thank you.
ps: Your project is really awesome!

**Comment by secgron** [comment]
> Hi there.
> I tried the subdomain checker API, it works like a charm!
> In the meta key, there's current page, max page, and total page. But how can I access them?
> Take a look at the example result.
> 
> ```json
> {
>   "meta": {
>     "total_pages": 139,
>     "query": "apex_domain = 'google.com'",
>     "page": 1,
>     "max_page": 100
>   }
> }
> ```
> 
> google.com has 100 max page, and my position is at the first page. Is it possible to access the second page? Thank you.
> ps: Your project is really awesome!

To move and looking forward for the second page, you only need to add &page=2. For example : 

```bash
$ curl https://api.hack.co.id/subdomain/?domain=google.com&page=2
```

Have a nice day!

**Comment by pr0ph0z** [comment]
Thank you for the response.
